### ISSUE TITLE
Use vraptor's convention

### ISSUE THREAD

**Issue by csokol** [caelum/vraptor-routes#7]
I think that vraptor-routes should consider the vraptor's convention when building the routes.

Right now, if the user does not define the route in the .properties file it throws an NPE: 

```
java.lang.NullPointerException
    at br.com.caelum.vraptor.routes.CustomRouterParser.getURIsFor(CustomRouterParser.java:51)
    at br.com.caelum.vraptor.http.route.PathAnnotationRoutesParser.registerRulesFor(PathAnnotationRoutesParser.java:101)
```

I think we should use the convetion in this case, or at least throw a better exception. What do you think?

**Comment by Turini** [comment]
I totally agree about using VRaptor's route convention.
